In [29]:
import numpy as np

matrix_3x4 = np.random.randint(1, 21, size=(3, 4))  # Generate numbers between 1 and 20
A = matrix_3x4[:, :3]  # Coefficient matrix (first 3 columns)
b = matrix_3x4[:, 3]   # Right-hand side vector (last column)

print("Generated 3x4 Matrix:")
print(matrix_3x4)
print("\nCoefficient Matrix (A):")
print(A)
print("\nRight-hand Side Vector (b):")
print(b)

# Step 2: Solve using the Matrix Inverse Method
try:
    A_inv = np.linalg.inv(A)  # Compute A^-1
    x_inverse_method = np.dot(A_inv, b)  # x = A^-1 * b
    print("\nSolution using Matrix Inverse Method:")
    print(x_inverse_method)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and cannot be inverted.")

# Step 3: Solve using Gaussian Elimination
x_gaussian = np.linalg.solve(A, b)  # Direct Gaussian elimination
print("\nSolution using Gaussian Elimination:")
print(x_gaussian)

# Step 4: Verify the solution
b_check = np.dot(A, x_gaussian)  # Recompute b using A and the computed x
print("\nVerification (Ax = b):")
print("Computed b:", b_check)
print("Original b:", b)

Generated 3x4 Matrix:
[[ 5 15 19 15]
 [18 11 12  4]
 [11 12  7  8]]

Coefficient Matrix (A):
[[ 5 15 19]
 [18 11 12]
 [11 12  7]]

Right-hand Side Vector (b):
[15  4  8]

Solution using Matrix Inverse Method:
[-0.4775641   1.05769231  0.08012821]

Solution using Gaussian Elimination:
[-0.4775641   1.05769231  0.08012821]

Verification (Ax = b):
Computed b: [15.  4.  8.]
Original b: [15  4  8]
